# Generated by Django 4.0.4 on 2022-06-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('avatar', models.ImageField(blank=True, max_length=350, upload_to='<django.db.models.fields.CharField>/avatar')),
                ('gender', models.CharField(blank=True, choices=[(None, ''), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=4)),
                ('date_of_birth', models.DateField()),
                ('join_date', models.DateField()),
            ],
            options={
                'ordering': ['-join_date', 'pseudo'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('comment_date', models.DateTimeField()),
                ('answers', models.ManyToManyField(blank=True, to='weblog.comment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog.blogger')),
            ],
            options={
                'ordering': ['-comment_date', 'author'],
                'get_latest_by': '-comment_date',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text_content', models.TextField(max_length=1500, unique=True)),
                ('post_date', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog.blogger')),
                ('categories', models.ManyToManyField(blank=True, to='weblog.category')),
            ],
            options={
                'ordering': ['-post_date', 'author', 'title'],
                'get_latest_by': '-post_date',
            },
        ),
    ]
