# Generated by Django 4.0.4 on 2022-06-04 11:21

from django.db import migrations, models
import weblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_blogger_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['-join_date', 'user']},
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='pseudo',
        ),
        migrations.AlterField(
            model_name='blogger',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=weblog.models.upload_to_user_directory),
        ),
    ]
