# Generated by Django 4.0.4 on 2022-06-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_alter_blogger_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_post_answered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weblog.blogpost'),
        ),
    ]
