# Generated by Django 4.0.4 on 2022-06-05 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_alter_blogpost_post_date_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 23, 3, 54, 140122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 23, 3, 54, 141378, tzinfo=utc)),
        ),
    ]
