# Generated by Django 4.0.4 on 2022-06-13 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weblog', '0011_alter_blogpost_post_date_alter_comment_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='text_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='answers',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comment_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.comment')),
            ],
            options={
                'ordering': ['-answer_date', 'author'],
                'get_latest_by': '-answer_date',
            },
        ),
    ]
