# Generated by Django 4.0.4 on 2022-06-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_rename_text_content_blogpost_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='gender',
        ),
    ]
