# Generated by Django 4.0.4 on 2022-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0015_alter_blogger_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
