# Generated by Django 4.0.5 on 2022-07-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0018_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user'], 'permissions': [('can_manage_blogger_data', 'Can manage blogger data')]},
        ),
    ]
