# Generated by Django 4.0.5 on 2022-07-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0019_alter_blogger_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user']},
        ),
    ]
